/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as ActivitesSlugRouteImport } from './routes/activites.$slug'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MeRouteImport } from './routes/me'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ProjetsSlugRouteImport } from './routes/projets.$slug'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TemoignagesRouteImport } from './routes/temoignages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesSlugRoute = ActivitesSlugRouteImport.update({
  id: '/activites/$slug',
  path: '/$slug',
  getParentRoute: () => ActivitesRoute,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/projets/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetsRoute,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/activites/$slug': typeof ActivitesSlugRoute
  '/actualites': typeof ActualitesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/projets': typeof ProjetsRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/activites/$slug': typeof ActivitesSlugRoute
  '/actualites': typeof ActualitesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/projets': typeof ProjetsRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/activites/$slug'
    | '/actualites'
    | '/actualites/$slug'
    | '/admin'
    | '/contact'
    | '/me'
    | '/projets'
    | '/projets/$slug'
    | '/services'
    | '/temoignages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/actualites'
    | '/admin'
    | '/contact'
    | '/me'
    | '/projets'
    | '/services'
    | '/temoignages'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/activites'
    | '/actualites'
    | '/admin'
    | '/contact'
    | '/me'
    | '/projets'
    | '/services'
    | '/temoignages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  ActivitesSlugRoute: typeof ActivitesSlugRoute
  ActualitesRoute: typeof ActualitesRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  MeRoute: typeof MeRoute
  ProjetsRoute: typeof ProjetsRoute
  ProjetsSlugRoute: typeof ProjetsSlugRoute
  ServicesRoute: typeof ServicesRoute
  TemoignagesRoute: typeof TemoignagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites/$slug': {
      id: '/activites/$slug'
      path: '/$slug'
      fullPath: '/activites/$slug'
      preLoaderRoute: typeof ActivitesSlugRouteImport
      parentRoute: typeof ActivitesRoute
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof ProjetsRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActivitesRoute: ActivitesRoute._addFileChildren({ ActivitesSlugRoute }),
  ActualitesRoute: ActualitesRoute._addFileChildren({ ActualitesSlugRoute }),
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  MeRoute: MeRoute,
  ProjetsRoute: ProjetsRoute._addFileChildren({ ProjetsSlugRoute }),
  ServicesRoute: ServicesRoute,
  TemoignagesRoute: TemoignagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
