// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function createSupabaseClient() {
  // LT GROUP production Supabase configuration.
  // Public client configuration is intentionally pinned to the production
  // project so a stale/misconfigured Vercel environment variable cannot
  // disconnect the public site from the correct database.
  const SUPABASE_URL = 'https://ghkijyimotuivykvwlge.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY =
    'sb_publishable_DOe49CSUFAbrDJZ4P2TawA_JlECROwj';

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
